### ISSUE TITLE
link rendered with spaces

### ISSUE THREAD

**Issue by Haroenv** [tachyons-css/tachyons-css.github.io#104]
> # Multiple Flavors
> 
> Don't like the class names? We've got a more verbose version you might like. Want to use Sass instead of Postcss? We've got a repo for that too :) Tachyons isn't just a css toolkit. It's a design system. Utitlized here in a `react native boilerplate`.

In the home page the piece I put in a code block had an structure: 

``` html
<a class="black dim" href"https:="" github.com="" tachyons-css="" react-native-style-tachyons"="">react native boilerplate.</a>
```

I couldn't find this sentence in the repository however...

**Comment by sebastienbarre** [comment]
I see it in several locations.

**Comment by Haroenv** [comment]
Why did you close this issue if you confirm it? Not sure if I understand your comment

**Comment by sebastienbarre** [comment]
Sorry, my misunderstanding then. I thought you were asking if your code has been merged, or had been added to the repo. Can you please clarify?

**Comment by sebastienbarre** [comment]
@Haroenv?

**Comment by Haroenv** [comment]
I was sleeping, sorry. I think this instance has been fixed. Thanks for helping out here ❤️
