### ISSUE TITLE
Tables of styles and properties pages missing content

### ISSUE THREAD

**Issue by keybits** [tachyons-css/tachyons-css.github.io#117]
http://tachyons.io/docs/table-of-properties/
http://tachyons.io/docs/table-of-styles/

are both missing content - here's how the latter renders for me:

![image](https://cloud.githubusercontent.com/assets/809823/20466869/17435e78-af73-11e6-854b-d530f4807a0f.png)

**Comment by johnotander** [comment]
Thanks for bringing this to our attention. We missed a step during the build process, but it should be fixed now!
