### ISSUE TITLE
Debug link is broken

### ISSUE THREAD

**Issue by mattrothenberg** [tachyons-css/tachyons-css.github.io#145]
On the following page, http://tachyons.io/docs/debug-grid/, the link to the **Debug** article is broken (and throws a 404) as it points to the incorrect URL.
```
http://tachyons.io/docs/layout/debug/
````

As the site is currently structured, it should point to:
```
http://tachyons.io/docs/debug/
```

**Comment by desiredpersona** [comment]
Hey Matt @mattrothenberg. 

Thanks. This issue can now be closed. We fixed it here #174
