### ISSUE TITLE
Flexbox in the docs?

### ISSUE THREAD

**Issue by dperrera** [tachyons-css/tachyons-css.github.io#168]
Should Flexbox be listed under "Layout" on the `/docs` page? I think it'd be helpful if were. I'm happy to help make it happen.

**Comment by lachlanjc** [comment]
For sure! I’ve written [documentation for the module](https://codepen.io/lachlanjc/pen/gRmXLe) but it needs to be integrated into the docs site.

**Comment by dperrera** [comment]
Closing this since flexbox is in the docs now 🎉
