### ISSUE TITLE
Error running `npm run components:watch`

### ISSUE THREAD

**Issue by donnieberg** [tachyons-css/tachyons-css.github.io#23]
Running `npm run components:watch` gave me a couple errors but I fixed them by adding `"css-selector-tokenizer": "^0.5.4"` and upgrading to ``"postcss": "^5.0.19"` (was 5.0.0) in package.json.

Before doing a PR, I wanted to see if I was doing something wrong. @mrmrs let me know :)

**Comment by johnotander** [comment]
PR those in! I overhauled the dependencies the other day and looks like I missed a few. My bad :blush:

**Comment by donnieberg** [comment]
Actually...I just needed to update my npm to 3.8.2 and the existing dependencies work just fine. I'm going to leave it as is but this might be good to note in the README.
