### ISSUE TITLE
Extra closing </div>s in Component Docs 

### ISSUE THREAD

**Issue by corderophilosophy** [tachyons-css/tachyons-css.github.io#68]
It looks like **Two Column** and **Two Column Collapse One** in Components > Layouts each seem to have extra closing div tags in the example text.  E.g. the example for **Two Column Collapse One** reads: 
```
<article class="cf">
  <div class="fl w-100 w-50-ns bg-near-white tc">
    <h1>Column One</h1>
  </div>
  <div class="fl w-100 w-50-ns bg-light-gray tc">
    <h1>Column Two</h1>
  </div>

  **</div>**
</article>
```

**Comment by johnotander** [comment]
Fixed thanks to @wizvishak
