### ISSUE TITLE
Menu overflow issue

### ISSUE THREAD

**Issue by balcsida** [tachyons-css/tachyons-css.github.io#70]
Menu displays vertical scrollbar, which is unnecessarry
![image](https://cloud.githubusercontent.com/assets/1768446/16560400/76995bea-41f3-11e6-8d87-f61d10bf6277.png)
Using overflow-auto instead overflow-container gives the desired result
![image](https://cloud.githubusercontent.com/assets/1768446/16560417/a06510cc-41f3-11e6-8338-8c7492592501.png)
![image](https://cloud.githubusercontent.com/assets/1768446/16560420/aa6d64c0-41f3-11e6-803f-000435735324.png)
#69

**Comment by mrmrs** [comment]
This has been fixed.
