### ISSUE TITLE
Separate components build for faster results

### ISSUE THREAD

**Issue by mrmrs** [tachyons-css/tachyons-css.github.io#92]
Few build / dev requests that would be nice to haves.

Would be great if we could run the components generation command only on the folder you are working within for faster feedback loops. Then you can run full list at end to make sure the navigation is updated globally. Also would be nice to be able to generate the components index page without regenerating all the components pages too.

**Comment by sebastienbarre** [comment]
I think this is covered by the changes I made to the build process. Closing.
